spring:
  data:
    mongodb:
      username: admin
      password: admin123
      host: localhost
      port: 27017
      database: fitness_activity
      authentication-database: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

server:
  port: 8086

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"


rabbitmq:
  exchange:
    name: fitness.exchange
  routing:
    key: activity.tracking
  queue:
    name: activity.queue
