spring:
  data:
    mongodb:
      username: ${ACTIVITY_DB_USERNAME}
      password: ${ACTIVITY_DB_PASSWORD}
      host: ${ACTIVITY_DB_HOST:localhost}
      port: ${ACTIVITY_DB_PORT:27017}
      database: ${ACTIVITY_DB_NAME:fitness_activity}
      authentication-database: admin
  rabbitmq:
    host: ${MQ_HOST:localhost}
    port: ${MQ_PORT:5672}
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}

server:
  port: 8086

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"


rabbitmq:
  exchange:
    name: fitness.exchange
  routing:
    key: activity.tracking
  queue:
    name: activity.queue
