spring:
  data:
    mongodb:
      username: ${FITNESS_DB_USERNAME}
      password: ${FITNESS_DB_PASSWORD}
      host: ${FITNESS_DB_HOST:localhost}
      port: ${FITNESS_DB_PORT:27017}
      database: ${FITNESS_DB_NAME:fitness_recommendation}
      authentication-database: admin
  rabbitmq:
    host: ${MQ_HOST:localhost}
    port: ${MQ_PORT:5672}
    username: ${MQ_USERNAME}
    password: ${MQ_PASSWORD}

server:
  port: 8087

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"

rabbitmq:
  exchange:
    name: fitness.exchange
  routing:
    key: activity.tracking
  queue:
    name: activity.queue

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}
