spring:
  datasource:
    url: jdbc:mysql://${USER_DB_HOST}:${USER_DB_PORT}/${USER_DB_NAME}
    username: ${USER_DB_USERNAME}
    password: ${USER_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8085

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
