spring:
  datasource:
    username: fitnessUser
    password: pass@123
    url: "jdbc:mysql://localhost:3306/fitness_userdb"

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8085

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
